### PR TITLE
Update README, mention dep on activerecord-postgres-hstore

### PR DESCRIPTION
**Pull request by damien**
First off, thanks so much for this gem. I've been using a similar hack for quite a while and it's nice to see a more polished version in gem form.

That being said, I had trouble getting this working in a brand new Rails 3.2.3 app. Upon running migrations, I'd get the following error:

```
undefined local variable or method `native_database_types_without_hstore' for #<ActiveRecord::ConnectionAdapters::PostgreSQLAdapter:0x007f9164197e48>
```

After some digging, it seems you were referencing methods from the `activerecord-postgres-hstore` gem. After including that in my Gemfile everything was hunky dory.

This patch is just some updates to the README to help out anyone who runs into similar issues. I wasn't sure if `activerecord-postgres-hstore` was intended to be a dependency of your gem, so I left the gemspec alone.

That's it! Thanks for the great gem!

### CODE REVIEW

**Comment by ivanvanderbyl** [comment]
Thanks for the feedback. I've actually fixed this issue locally and will push an update tomorrow. 

Regards,
Ivan Vanderbyl
